name: Build Snap Package

on:
  push:
    branches:
      - main
      - 'photosensitive-version'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v6

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: build
        with:
          path: .

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v7
        with:
          name: teatime-accessibility-snap
          path: ${{ steps.build.outputs.snap }}
