name: Build and Release Snap

on:
  push:
    branches:
      - main
      - 'photosensitive-version'
      - 'kcresonance'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v6

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: build
        with:
          path: .

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v7
        with:
          name: teatime-accessibility-snap
          path: ${{ steps.build.outputs.snap }}

      - name: Publish to Snap Store
        # This step will only run if the SNAPCRAFT_TOKEN secret is present
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/photosensitive-version' || github.ref == 'refs/heads/kcresonance')
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ github.ref == 'refs/heads/main' && 'stable' || (github.ref == 'refs/heads/photosensitive-version' && 'beta' || 'edge') }}
